### ISSUE TITLE
Thx A Lot!!!!!

### ISSUE THREAD

**Issue by leeduckgo** [exthereum/libsecp256k1#23]
I want to find a ex-library containing `:libsecp256k1.ecdsa_sign_compact` func , but `mbrix/libsecp256k1` compile failed and I cant' find anyother userful Library.

This Repo is the Only Repo IN GITHUB That worked!!!!!

Thx a lot again.

**Comment by hayesgm** [comment]
Glad to hear it! Let me know if you need anything :)
